services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: serviceDeStage_Db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - spring-demo

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
  pgadmin-data:
