services:
  postgres:
    container_name: postgres-sql-stage
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: serviceDeStage_Db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - spring-project


networks:
  spring-project:
    driver: bridge

volumes:
  postgres:

