spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nourichadi70@gmail.com
    password: snuo vpkw hfne zmvb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    context-path: /api




